# ruff: noqa: INP001, T201
"""Generate the behaviour-freeze corpus seed list (Phase 0 of the refactor).

The corpus is the safety net for every later refactor phase: it records what
the pipeline produces today so a semantic diff can prove a change was
behaviour-preserving. It therefore has to be *reproducible* — regenerating it
must yield byte-identical output — so selection is a deterministic stride over
the sorted seed list, never `random.sample`.

`data/my-seeds.txt` holds only two-segment repository URLs, so the user- and
organization-rooted code paths (`PLAN_BY_TYPE` has one plan per detected type)
would go untested. Owner URLs are derived from the sampled repositories to
cover them; `classify_url` decides User vs Organization at runtime, which is
what we want to exercise.

Usage:
    python scripts/v2/make_corpus_seeds.py [--repos 90] [--owners 30]
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE = REPO_ROOT / "data" / "my-seeds.txt"
# Tracked on purpose: `data/` is gitignored, and the corpus *definition* is
# part of the contract even though the recorded outputs are regenerable.
OUTPUT = REPO_ROOT / "tests" / "v2" / "corpus" / "seeds.txt"

DEFAULT_REPOS = 90
DEFAULT_OWNERS = 30


def _read_seeds() -> list[str]:
    if not SOURCE.exists():
        message = f"seed list not found: {SOURCE}"
        raise SystemExit(message)
    seen: set[str] = set()
    seeds: list[str] = []
    for raw in SOURCE.read_text(encoding="utf-8").splitlines():
        url = raw.strip()
        if not url or url.startswith("#") or url in seen:
            continue
        seen.add(url)
        seeds.append(url)
    return sorted(seeds)


def _stride_sample(items: list[str], count: int) -> list[str]:
    """Take `count` items spread evenly across `items`, deterministically."""
    if count >= len(items):
        return list(items)
    step = len(items) / count
    return [items[int(index * step)] for index in range(count)]


def _owner_of(url: str) -> str | None:
    tail = url.partition("github.com/")[2]
    owner = tail.split("/", maxsplit=1)[0].strip()
    return owner or None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repos", type=int, default=DEFAULT_REPOS)
    parser.add_argument("--owners", type=int, default=DEFAULT_OWNERS)
    args = parser.parse_args()

    seeds = _read_seeds()
    repos = _stride_sample(seeds, args.repos)

    # Distinct owners, drawn from the whole seed list rather than only the
    # sampled repositories, so owner coverage does not shrink with --repos.
    owners_seen: set[str] = set()
    owner_pool: list[str] = []
    for url in seeds:
        owner = _owner_of(url)
        if owner is None or owner.lower() in owners_seen:
            continue
        owners_seen.add(owner.lower())
        owner_pool.append(f"https://github.com/{owner}")
    owners = _stride_sample(owner_pool, args.owners)

    lines = [
        "# Behaviour-freeze corpus — Phase 0 of the ontology-first refactor.",
        "#",
        "# Generated by scripts/v2/make_corpus_seeds.py. Do not hand-edit:",
        "# regenerate so the selection stays reproducible.",
        f"# source={SOURCE.relative_to(REPO_ROOT)} unique_seeds={len(seeds)}",
        f"# repositories={len(repos)} owners={len(owners)}",
        "",
        "# --- repositories (detected_type=repository) ---",
        *repos,
        "",
        "# --- owners (detected_type=user or organization, decided by classify_url) ---",
        *owners,
        "",
    ]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  {len(repos)} repositories + {len(owners)} owners = {len(repos) + len(owners)} URLs")
    print(f"  drawn deterministically from {len(seeds)} unique seeds")


if __name__ == "__main__":
    main()
