"""Build a raw-profile instance graph from REAL captured API responses.

Input:  tests/v2/fixtures/providers/live_snapshots/  (the `gimie-baseline`
        dataset — real GitHub / ROR / ORCID responses captured 2026-02-24,
        each with a .meta.json carrying the request URL and captured_at)
Output: dev/v4.0.0/examples/gimie-raw-instance.ttl

This is the conversion test: can the proposed raw profile actually hold what
we extract? Nothing here is invented — every literal traces to a snapshot
field, and every provenance timestamp is the real capture time.

Run:  python dev/v4.0.0/build_instance_example.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SNAP = ROOT / "tests" / "v2" / "fixtures" / "providers" / "live_snapshots"
OUT = ROOT / "dev" / "v4.0.0" / "examples" / "gimie-raw-instance.ttl"

RUN = "urn:pulse:run:gimie-baseline"
OUT_GH = "urn:pulse:output:gimie-baseline:github"
OUT_ROR = "urn:pulse:output:gimie-baseline:ror"


def load(rel: str) -> dict | list:
    return json.loads((SNAP / rel).read_text(encoding="utf-8"))


def esc(s: str) -> str:
    t = str(s).replace("\\", "\\\\").replace('"', '\\"')
    # Collapse ALL whitespace. Real payloads carry \r\n (an ORCID biography
    # broke the first run with "newline found in string literal"), tabs and
    # stray control characters.
    return " ".join(t.split())


def hashed_email(addr: str) -> tuple[str, str]:
    """Our privacy policy: hashed local part, domain kept (privacy.py)."""
    local, _, domain = addr.partition("@")
    return hashlib.sha256(local.encode()).hexdigest()[:12], domain


# ---------------------------------------------------------------- load real data
repo = load("github/repo_sdsc-ordes_gimie.response.json")
repo_meta = load("github/repo_sdsc-ordes_gimie.meta.json")
contribs = load("github/contributors_sdsc-ordes_gimie.response.json")
contribs_meta = load("github/contributors_sdsc-ordes_gimie.meta.json")
langs = load("github/languages_sdsc-ordes_gimie.response.json")
org = load("github/org_sdsc-ordes.response.json")
org_meta = load("github/org_sdsc-ordes.meta.json")
ror = load("ror/org_02s376052.response.json")
ror_meta = load("ror/org_02s376052.meta.json")

REPO_IRI = repo["html_url"]                       # https://github.com/sdsc-ordes/gimie
ORG_GH_IRI = org["html_url"]
captured = repo_meta["captured_at"]

L: list[str] = []
add = L.append

add("""# Raw-profile instance graph — REAL data, not a hand-written example.
#
# Source: tests/v2/fixtures/providers/live_snapshots/ ("gimie-baseline"),
# real GitHub / ROR responses captured 2026-02-24T14:18:28Z. Every literal
# below traces to a snapshot field; every retrievedFrom/retrievedAt is the
# actual request URL and capture time from the .meta.json sidecars.
#
# Generated by dev/v4.0.0/build_instance_example.py — do not hand-edit.

@prefix schema: <http://schema.org/> .
@prefix org:    <http://www.w3.org/ns/org#> .
@prefix pulse:  <https://open-pulse.epfl.ch/ontology#> .
@prefix prov:   <http://www.w3.org/ns/prov#> .
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:   <http://www.w3.org/2004/02/skos/core#> .
@prefix time:   <http://www.w3.org/2006/time#> .
""")

# ---------------------------------------------------------------- extraction run
add(f"""# --- the extraction run and its per-platform outputs (§18(2)) ---
<{RUN}> a pulse:ExtractionRun ;
    prov:startedAtTime "{captured}"^^xsd:dateTime ;
    pulse:extractionSeed "sdsc-ordes/gimie" ;
    pulse:extractedBy <urn:pulse:agent:gme-3.0.0> .

<urn:pulse:agent:gme-3.0.0> a prov:SoftwareAgent ;
    schema:name "git-metadata-extractor" ;
    schema:softwareVersion "3.0.0" .

<{OUT_GH}> a pulse:ExtractionOutput ;
    prov:wasGeneratedBy <{RUN}> ;
    pulse:platform pulse:GitHub ;
    prov:generatedAtTime "{captured}"^^xsd:dateTime .

<{OUT_ROR}> a pulse:ExtractionOutput ;
    prov:wasGeneratedBy <{RUN}> ;
    pulse:platform pulse:ROR ;
    prov:generatedAtTime "{ror_meta['captured_at']}"^^xsd:dateTime .
""")

# ---------------------------------------------------------------- repository
primary_lang = max(langs, key=langs.get) if langs else None
# GME emits an SPDX license IRI, not a bare id — repository_agent.py
# _normalize_license_url(): https://spdx.org/licenses/{spdx_id}.html
_spdx = (repo.get("license") or {}).get("spdx_id")
license_iri = f"https://spdx.org/licenses/{_spdx}.html"
lang_lines = " ,\n        ".join(f'"{esc(k)}"' for k in sorted(langs))

add(f"""# --- the repository. Terms marked (+) are proposed in ontology.ttl ---
<{REPO_IRI}> a schema:SoftwareSourceCode ;
    schema:name "{esc(repo['name'])}" ;
    schema:description "{esc(repo['description'] or '')}" ;
    schema:url <{repo['html_url']}> ;
    pulse:platform pulse:GitHub ;
    pulse:repositoryHandle "{esc(repo['full_name'])}" ;
    pulse:platformInternalId "{repo['id']}" ;
    pulse:platformNodeId "{esc(repo['node_id'])}" ;
    pulse:repositoryStars {repo['stargazers_count']} ;
    pulse:repositoryForks {repo['forks_count']} ;
    schema:dateCreated "{repo['created_at']}"^^xsd:dateTime ;
    schema:dateModified "{repo['updated_at']}"^^xsd:dateTime ;
    pulse:pushedDate "{repo['pushed_at']}"^^xsd:dateTime ;
    schema:license <{license_iri}> ;
    schema:programmingLanguage {lang_lines} ;
    pulse:ownedBy <{ORG_GH_IRI}> ;
    pulse:visibility pulse:PublicVisibility ;
    pulse:archived {str(repo['archived']).lower()} ;
    pulse:isTemplate {str(repo.get('is_template', False)).lower()} ;
    pulse:defaultBranch "{esc(repo['default_branch'])}" ;
    pulse:watcherCount {repo['subscribers_count']} ;
    pulse:openIssueCount {repo['open_issues_count']} ;
    pulse:hasDiscussions {str(repo['has_discussions']).lower()} ;
    pulse:hasWiki {str(repo['has_wiki']).lower()} ;
    pulse:hasPages {str(repo['has_pages']).lower()} ;
    pulse:hasIssues {str(repo['has_issues']).lower()} ;          # (+) §3
    pulse:hasProjects {str(repo['has_projects']).lower()} ;      # (+) §3
    pulse:sizeInBytes {repo['size'] * 1024} ;                    # (+) §4 (API gives KB)
    pulse:forkNetworkCount {repo.get('network_count', repo['forks_count'])} ;  # (+) §4
    pulse:primaryProgrammingLanguage "{esc(primary_lang or '')}" ;  # (+) §4
    pulse:partOfRun <{OUT_GH}> .
""")

# ---------------------------------------------------------------- unmapped fields
# §18(5): real GitHub fields with no term anywhere. Kept, not dropped.
UNMAPPED = ["allow_forking", "has_downloads", "web_commit_signoff_required",
            "allow_merge_commit", "delete_branch_on_merge", "watchers_count"]
present = [(k, repo[k]) for k in UNMAPPED if k in repo]
add("# --- §18(5): real fields with no term — preserved instead of dropped ---")
for i, (k, v) in enumerate(present):
    node = f"urn:pulse:unmapped:gimie:{k}"
    add(f"""<{REPO_IRI}> pulse:hasUnmappedField <{node}> .
<{node}> a pulse:UnmappedField ;
    pulse:sourceFieldName "{k}" ;
    pulse:rawValue "{esc(str(v))}" .""")
add("")

# ---------------------------------------------------------------- organization
ror_id = ror.get("id") or "https://ror.org/02s376052"
ror_name = ror.get("name") or (ror.get("names") or [{}])[0].get("value", "")
established = ror.get("established")

add(f"""# --- the organization: GitHub profile + ROR authority record ---
<{ORG_GH_IRI}> a org:Organization ;
    schema:name "{esc(org.get('name') or org['login'])}" ;
    pulse:organizationHandle "{esc(org['login'])}" ;
    schema:url <{org['html_url']}> ;
    pulse:partOfRun <{OUT_GH}> .

<urn:pulse:orgprofile:github:{org['login']}> a pulse:OrganizationProfile ;
    pulse:platform pulse:GitHub ;
    pulse:organizationProfileOf <{ORG_GH_IRI}> ;
    pulse:organizationHandle "{esc(org['login'])}" ;
    schema:name "{esc(org.get('name') or org['login'])}" ;
    schema:url <{org['html_url']}> ;
    pulse:platformInternalId "{org['id']}" ;
    schema:description "{esc(org.get('description') or '')}" ;
    pulse:followerCount {org.get('followers', 0)} ;
    schema:dateModified "{org['updated_at']}"^^xsd:dateTime ;
    pulse:partOfRun <{OUT_GH}> .
""")

if established:
    add(f"""# ROR registry facts on the organization itself (§15 preferred form)
<{ror_id}> a org:Organization ;
    schema:name "{esc(ror_name)}" ;
    pulse:establishedYear "{established}"^^xsd:gYear ;    # (+) §5
    pulse:partOfRun <{OUT_ROR}> .
""")

# ---------------------------------------------------------------- people
add("# --- contributors: provisional Person + one PlatformProfile each (§2 of the assessment) ---")
for c in contribs:
    login = c["login"]
    person = f"urn:pulse:person:github:{login}"
    profile = f"urn:pulse:profile:github:{login}"
    contribution = f"urn:pulse:contribution:{login}__gimie"
    if c.get("type") != "User":
        continue
    add(f"""<{person}> a schema:Person ;
    schema:name "{esc(login)}" ;
    pulse:hasProfile <{profile}> ;
    pulse:hasContribution <{contribution}> ;
    pulse:partOfRun <{OUT_GH}> .

<{profile}> a pulse:PlatformProfile ;
    pulse:platform pulse:GitHub ;
    pulse:profileOf <{person}> ;
    pulse:platformUsername "{esc(login)}" ;
    pulse:platformInternalId "{c['id']}" ;
    pulse:platformNodeId "{esc(c['node_id'])}" ;
    schema:url <{c['html_url']}> ;
    schema:image <{c['avatar_url']}> ;
    pulse:partOfRun <{OUT_GH}> .

<{contribution}> a pulse:Contribution ;
    pulse:contributionTo <{REPO_IRI}> ;
    schema:author <{person}> ;
    pulse:contributionCount {c['contributions']} ;
    pulse:partOfRun <{OUT_GH}> .
""")

# ---------------------------------------------------------------- git identities
# The contributors API gives logins, not commit identities, so these are the
# GitHub noreply forms the platform itself issues — real, and pseudonymous.
add("# --- §9 GitIdentity: hashed local part + domain, per our privacy policy ---")
for c in contribs[:3]:
    if c.get("type") != "User":
        continue
    login = c["login"]
    addr = f"{c['id']}+{login}@users.noreply.github.com"
    h, domain = hashed_email(addr)
    gid = f"urn:pulse:gitidentity:{login}"
    add(f"""<urn:pulse:contribution:{login}__gimie> pulse:hasGitIdentity <{gid}> .
<{gid}> a pulse:GitIdentity ;
    pulse:gitAuthorName "{esc(login)}" ;
    pulse:gitAuthorEmailHash "{h}" ;
    pulse:gitAuthorEmailDomain "{domain}" ;
    pulse:gitIdentityRole "author" ;
    pulse:isPseudonymousEmail true ;
    pulse:isBotIdentity false ;
    pulse:contributionCount {c['contributions']} ;
    pulse:partOfRun <{OUT_GH}> .""")
add("")

# ---------------------------------------------------------------- observations
add("# --- §18(4) provenance: where each value came from, and when it was queried ---")
for i, (meta, subj, prop, val) in enumerate([
    (repo_meta, REPO_IRI, "pulse:repositoryStars", str(repo["stargazers_count"])),
    (contribs_meta, REPO_IRI, "pulse:contributionCount", str(sum(c["contributions"] for c in contribs))),
    (org_meta, ORG_GH_IRI, "schema:name", esc(org.get("name") or org["login"])),
    (ror_meta, ror_id, "pulse:establishedYear", str(established or "")),
]):
    obs = f"urn:pulse:obs:{i}"
    add(f"""<{obs}> a pulse:Observation ;
    pulse:observedSubject <{subj}> ;
    pulse:observedProperty {prop} ;
    pulse:observedValue "{val}" ;
    pulse:retrievedFrom <{meta['request']['url']}> ;
    pulse:retrievedAt "{meta['captured_at']}"^^xsd:dateTime ;
    pulse:sourcePlatform pulse:{'ROR' if meta['provider'] == 'ror' else 'GitHub'} ;
    pulse:observationKind "single-source" .""")

OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}  ({len(L)} blocks)")
