"""Materialize the raw profile AS WE PROPOSE IT, as real files.

Until now the proposed shape changes (asks #13, #14, #22) existed only as an
in-memory simulation inside the validator. This writes them out, so the
ontology team can diff a file instead of reading a description — and so the
conversion test can validate against the file rather than a simulation.

Inputs  : the upstream raw profile, fetched at a pinned commit.
Outputs : dev/v4.0.0/proposed/
            ontology-shapes-raw.proposed.ttl
            ontology-definitions-raw.proposed.ttl
            ontology-enumerations-raw.proposed.ttl

Patching is TEXTUAL, not a re-serialization: their comments, ordering and
formatting survive, so `diff` shows only what we actually changed.

Run:  python dev/v4.0.0/materialize_proposed_raw.py
"""
from __future__ import annotations

import re
from pathlib import Path

import requests

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "proposed"
OUTDIR.mkdir(exist_ok=True)

# Pinned so the output is reproducible; bump deliberately.
REF = "290579dd7dfe"
BASE = f"https://raw.githubusercontent.com/sdsc-ordes/open-pulse-ontology/{REF}/src/ontology"

HEADER = """# ============================================================================
# {name} — THE RAW PROFILE AS git-metadata-extractor PROPOSES IT
#
# DERIVED WORK. Source: sdsc-ordes/open-pulse-ontology, branch
# feature/platform-profiles, commit {ref}, file {orig}.
# Upstream is licensed CC-BY-SA-4.0; this derivative carries the same licence
# and the same attribution.
#
# Generated by dev/v4.0.0/materialize_proposed_raw.py — do not hand-edit.
# Every change is listed below and argued in ../ontology.ttl and ../README.md.
#
# CHANGES APPLIED
{changes}
# ============================================================================

"""


def fetch(name: str) -> str:
    r = requests.get(f"{BASE}/{name}", timeout=60)
    r.raise_for_status()
    return r.text


def patch_shapes(text: str) -> tuple[str, list[str]]:
    changes: list[str] = []

    # --- ask #13: raw is the intake; an intake cannot reject unanticipated input
    n_closed = text.count("sh:closed true")
    text = text.replace("sh:closed true", "sh:closed false")
    changes.append(f"#   #13  sh:closed true -> false on {n_closed} node shapes")

    # --- ask #22: one entity can be seen by several platforms
    #     drop sh:maxCount 1 from the pulse:partOfRun property blocks only
    def drop_maxcount(m: re.Match) -> str:
        block = m.group(0)
        return re.sub(r"\n\s*sh:maxCount 1 ;", "", block)

    text, n_mc = re.subn(
        r"sh:property \[\s*\n\s*sh:path pulse:partOfRun ;(?:[^\]]*?)\]",
        drop_maxcount,
        text,
    )
    changes.append(f"#   #22  removed sh:maxCount 1 from {n_mc} partOfRun property shapes")

    # --- ask #14: every raw node shape must be able to name its run
    shapes = re.findall(r"^(pulse:\w+Shape)\b", text, flags=re.MULTILINE)
    blocks = re.split(r"(?m)^(?=pulse:\w+Shape\b)", text)
    missing = []
    # Two deliberate exclusions:
    #   sh:PropertyShape — a reusable property fragment, not a node; partOfRun
    #     on it would be meaningless.
    #   ExtractionOutputShape — the output IS the run's product and links via
    #     prov:wasGeneratedBy; making it partOfRun another output is circular.
    EXCLUDE = {"pulse:ExtractionOutputShape"}
    for shape in dict.fromkeys(shapes):
        blk = next((b for b in blocks if b.startswith(shape + "\n") or b.startswith(shape + " ")), "")
        if shape in EXCLUDE or "a sh:PropertyShape" in blk:
            continue
        if "pulse:partOfRun" not in blk:
            missing.append(shape)
    if missing:
        text += (
            "\n\n# ---------------------------------------------------------\n"
            "# ASK #14 — pulse:partOfRun on every raw node shape.\n"
            "#\n"
            "# Added as standalone statements rather than edited into the blocks\n"
            "# above, so the diff stays minimal and their formatting survives.\n"
            "# Without these, the nodes that exist to hold one platform's view of\n"
            "# an entity cannot say which ExtractionOutput produced them — which is\n"
            "# the backbone of the provenance profile.\n"
            "# ---------------------------------------------------------\n\n"
        )
        for shape in missing:
            text += (
                f"{shape} sh:property [\n"
                f"    sh:path pulse:partOfRun ;\n"
                f"    sh:class pulse:ExtractionOutput ;\n"
                f'    sh:name "Part Of Run"\n'
                f"] .\n"
            )
        changes.append(f"#   #14  added partOfRun to {len(missing)} shapes: {', '.join(s.split(':')[1] for s in missing)}")

    # --- our new shapes (RawContribution / RawGitIdentity / RawProject)
    additions = (HERE / "ontology-shapes-raw.additions.ttl").read_text(encoding="utf-8")
    body = additions.split("@prefix prov:", 1)[-1].split("\n", 1)[-1]
    text += (
        "\n\n# ---------------------------------------------------------\n"
        "# NEW SHAPES — from ontology-shapes-raw.additions.ttl\n"
        "# ---------------------------------------------------------\n" + body
    )
    changes.append("#   #2/#19  added RawContributionShape, RawGitIdentityShape, RawProjectShape")
    return text, changes


def missing_prefixes(target: str) -> str:
    """Our alignment targets need prefixes upstream does not declare.

    Turtle allows @prefix at any top-level position, applying to what follows,
    so these are emitted immediately before the appended block rather than
    rewriting the file header.
    """
    ours = (HERE / "ontology.ttl").read_text(encoding="utf-8")
    lines = []
    for ln in ours.splitlines():
        if not ln.startswith("@prefix"):
            continue
        pfx = ln.split()[1]
        if f"@prefix {pfx}" not in target:
            lines.append(ln)
    return "\n".join(lines) + ("\n\n" if lines else "")


def patch_definitions(text: str) -> tuple[str, list[str]]:
    ours = (HERE / "ontology.ttl").read_text(encoding="utf-8")
    # keep only the term declarations, not our 22 sections of argument
    kept = [
        ln for ln in ours.splitlines()
        if ln and not ln.startswith("#") and not ln.startswith("@prefix")
    ]
    text += (
        "\n\n# ---------------------------------------------------------\n"
        "# PROPOSED TERMS — see ../ontology.ttl for the argument behind each,\n"
        "# and ../verification.md for the evidence that every external IRI\n"
        "# referenced here exists.\n"
        "# ---------------------------------------------------------\n\n"
        + missing_prefixes(text)
        + "\n".join(kept) + "\n"
    )
    return text, ["#   proposed classes, properties and alignment axioms appended"]


def write(name: str, orig: str, text: str, changes: list[str]) -> None:
    head = HEADER.format(name=name, ref=REF, orig=orig, changes="\n".join(changes))
    (OUTDIR / name).write_text(head + text, encoding="utf-8")
    print(f"  {name:44} {len(text.splitlines()):5} lines")
    for c in changes:
        print(f"      {c.lstrip('# ')}")


print(f"fetching the upstream raw profile at {REF}")
shapes_src = fetch("ontology-shapes-raw.ttl")
defs_src = fetch("ontology-definitions-raw.ttl")
enums_src = fetch("ontology-enumerations-raw.ttl")
print(f"  upstream: shapes {len(shapes_src.splitlines())} lines, "
      f"definitions {len(defs_src.splitlines())}, enumerations {len(enums_src.splitlines())}\n")

shapes_out, shape_changes = patch_shapes(shapes_src)
defs_out, def_changes = patch_definitions(defs_src)

# enumerations: our proposed members, extracted from ontology.ttl by type
ours = (HERE / "ontology.ttl").read_text(encoding="utf-8")
members = re.findall(r"^(pulse:\w+\s+a\s+pulse:\w+Enumeration\s*;.*?)\.\s*$", ours,
                     flags=re.MULTILINE | re.DOTALL)
enums_out = enums_src + (
    "\n\n# ---------------------------------------------------------\n"
    "# PROPOSED ENUMERATION MEMBERS — platforms, identifier schemes, package\n"
    "# ecosystems, deposit relations, publication types, membership types.\n"
    "# ---------------------------------------------------------\n\n"
    + missing_prefixes(enums_src)
    + "\n\n".join(m.strip() + " ." for m in members) + "\n"
)

write("ontology-shapes-raw.proposed.ttl", "ontology-shapes-raw.ttl", shapes_out, shape_changes)
write("ontology-definitions-raw.proposed.ttl", "ontology-definitions-raw.ttl", defs_out, def_changes)
write("ontology-enumerations-raw.proposed.ttl", "ontology-enumerations-raw.ttl", enums_out,
      [f"#   appended {len(members)} proposed enumeration members"])
print(f"\nwrote to {OUTDIR}")
