# generated by datamodel-codegen:
#   filename:  bundle.schema.json
# source-schema-sha256:
# - article.schema.json: 9493d56d6cbc441aa5061c38e4392b70f76b9c41eb4424f5f0f74bc3c5f12028
# - contribution.schema.json: ac7d1bdb429a359e9e10045faf4874d6575b02e14277e959a5c979af15e456f8
# - membership.schema.json: 7ec7bd52823ad40aca2e1bafb1747ac54ec6a8a99ac42ccd563c5bbaab004ceb
# - organization.schema.json: ff152525b13e7caa4df6d5328945ce32a5fb7cd458211bad4840fc94df1613d4
# - person.schema.json: 1b397c3c524574bae63a333249816f85334c1e7420075a37a4e444004d3ae11a
# - repository.schema.json: 0c4d0081ec6ea0953735e1d4a25a08c69d306e9c3acb7964748dff47afdaa9e7
#

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from enum import Enum


class Identifiers(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    pulse_orcid: str | None = Field(
        None,
        alias="pulse:orcid",
        description="ORCID identifier. Format: four groups of 4 digits separated by hyphens, last character can be 0-9 or X. Example: '0000-0001-2345-6789'",
    )
    pulse_infosciencePersonIdentifier: str | None = Field(
        None,
        alias="pulse:infosciencePersonIdentifier",
        description="Infoscience person UUID4 identifier. Format: 8-4-4-4-12 hexadecimal characters. Example: 'f97b60da-bcab-4f2e-ba12-0ee0c4d0d6eb'",
    )
    pulse_githubUsername: str | None = Field(
        None,
        alias="pulse:githubUsername",
        description="GitHub username. Example: 'caviri'",
    )
    uuid: str | None = Field(
        None,
        description="UUID4 fallback identifier. Always present. Format: 8-4-4-4-12 hexadecimal characters. Example: 'a7d4e2b1-3c8f-4a5b-9d6e-2f1a3b4c5d6e'",
    )


class AgentPersonShape(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier. Set to the first non-null value from: pulse:orcid, pulse:infosciencePersonIdentifier, pulse:githubUsername, or uuid (fallback). Example: '0000-0001-2345-6789' or 'mweber'",
    )
    type: str = Field(..., description="RDF type. Must be 'schema:Person'")
    shacl: str = Field(
        ..., description="SHACL shape reference. Must be 'pulse:PersonShape'"
    )
    identifiers: Identifiers = Field(
        ...,
        description="All available identifiers for this person. Contains pulse:orcid, pulse:infosciencePersonIdentifier, pulse:githubUsername, and uuid (always present)",
    )
    idSource: str = Field(
        ...,
        description="Indicates which identifier was used as the primary 'id'. One of: 'pulse:orcid', 'pulse:infosciencePersonIdentifier', 'pulse:githubUsername', or 'uuid'",
    )
    schema_name: str = Field(
        ...,
        alias="schema:name",
        description="Full name of the person. REQUIRED per SHACL. Example: 'Carlos Vivar Rios'",
    )
    schema_email: str | None = Field(
        None,
        alias="schema:email",
        description="Email address. Format: standard email pattern. Example: 'carlos.vivar@epfl.ch'",
    )
    schema_url: str | None = Field(
        None,
        alias="schema:url",
        description="Profile URL for personal webpage. Example: 'https://caviri.github.io'",
    )
    pulse_githubUsername: str | None = Field(
        None,
        alias="pulse:githubUsername",
        description="GitHub username. Example: 'caviri'",
    )
    pulse_orcidIdentifier: str | None = Field(
        None,
        alias="pulse:orcidIdentifier",
        description="ORCID identifier. Format: 0000-0001-2345-6789 (four groups of 4 digits, last can be X). Example: '0000-0001-2345-6789'",
    )
    pulse_infosciencePersonIdentifier: str | None = Field(
        None,
        alias="pulse:infosciencePersonIdentifier",
        description="Infoscience person UUID4 identifier. Example: 'f97b60da-bcab-4f2e-ba12-0ee0c4d0d6eb'",
    )
    org_hasMembership: list[str] | None = Field(
        None,
        alias="org:hasMembership",
        description="Array of MembershipShape IDs. Format: composite (personId_orgId). Example: ['0000-0001-2345-6789_https://ror.org/02s376052']",
    )
    pulse_hasContribution: list[str] | None = Field(
        None,
        alias="pulse:hasContribution",
        description="Array of ContributionShape IDs. Format: composite (personId_repoId). Example: ['0000-0001-2345-6789_EPFL-ENAC/geodata-toolkit']",
    )
    pulse_owns: list[str] | None = Field(
        None,
        alias="pulse:owns",
        description="Array of RepositoryShape IDs owned by this person. Format: GitHub handle (owner/repo). Example: ['EPFL-ENAC/geodata-toolkit']",
    )


class Identifiers1(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    pulse_githubRepositoryHandle: str | None = Field(
        None,
        alias="pulse:githubRepositoryHandle",
        description="GitHub repository handle. Format: owner/repo. Example: 'EPFL-ENAC/geodata-toolkit'",
    )
    schema_citation: str | None = Field(
        None,
        alias="schema:citation",
        description="DOI identifier. Example: 'https://doi.org/10.5281/zenodo.1234567845678'",
    )
    uuid: str | None = Field(
        None,
        description="UUID4 fallback identifier. Always present. Example: 'b1c2d3e4-5f6a-4b7c-8d9e-0f1a2b3c4d5e'",
    )


class PulseRepositoryType(Enum):
    pulse_Software = "pulse:Software"
    pulse_Data = "pulse:Data"
    pulse_Documentation = "pulse:Documentation"
    pulse_EducationalResource = "pulse:EducationalResource"
    pulse_Other = "pulse:Other"


class PulseDisciplineEnum(Enum):
    wd_Q1254373 = "wd:Q1254373"
    wd_Q101333 = "wd:Q101333"
    wd_Q1071 = "wd:Q1071"
    wd_Q11680831 = "wd:Q11680831"
    wd_Q12271 = "wd:Q12271"
    wd_Q12483 = "wd:Q12483"
    wd_Q18351432 = "wd:Q18351432"
    wd_Q188847 = "wd:Q188847"
    wd_Q192386 = "wd:Q192386"
    wd_Q21201 = "wd:Q21201"
    wd_Q2167061 = "wd:Q2167061"
    wd_Q2329 = "wd:Q2329"
    wd_Q23404 = "wd:Q23404"
    wd_Q2878974 = "wd:Q2878974"
    wd_Q309 = "wd:Q309"
    wd_Q333 = "wd:Q333"
    wd_Q3353193 = "wd:Q3353193"
    wd_Q34749 = "wd:Q34749"
    wd_Q3606845 = "wd:Q3606845"
    wd_Q395 = "wd:Q395"
    wd_Q413 = "wd:Q413"
    wd_Q420 = "wd:Q420"
    wd_Q42240 = "wd:Q42240"
    wd_Q428691 = "wd:Q428691"
    wd_Q43035 = "wd:Q43035"
    wd_Q4830453 = "wd:Q4830453"
    wd_Q580689 = "wd:Q580689"
    wd_Q5891 = "wd:Q5891"
    wd_Q7112556 = "wd:Q7112556"
    wd_Q7163 = "wd:Q7163"
    wd_Q735 = "wd:Q735"
    wd_Q7748 = "wd:Q7748"
    wd_Q77590 = "wd:Q77590"
    wd_Q7991 = "wd:Q7991"
    wd_Q8008 = "wd:Q8008"
    wd_Q80083 = "wd:Q80083"
    wd_Q8078 = "wd:Q8078"
    wd_Q8134 = "wd:Q8134"
    wd_Q8162 = "wd:Q8162"
    wd_Q816264 = "wd:Q816264"
    wd_Q8242 = "wd:Q8242"
    wd_Q83588 = "wd:Q83588"
    wd_Q8434 = "wd:Q8434"
    wd_Q843601 = "wd:Q843601"
    wd_Q9174 = "wd:Q9174"
    wd_Q9418 = "wd:Q9418"


class AgentRepositoryShape(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier. Set to the first non-null value from: pulse:githubRepositoryHandle, schema:citation (DOI), or uuid (fallback). Example: 'EPFL-ENAC/geodata-toolkit'",
    )
    type: str = Field(..., description="RDF type. Must be 'schema:SoftwareSourceCode'")
    shacl: str = Field(
        ..., description="SHACL shape reference. Must be 'pulse:RepositoryShape'"
    )
    identifiers: Identifiers1 = Field(
        ...,
        description="All available identifiers for this repository. Contains pulse:githubRepositoryHandle, schema:citation (DOI), and uuid",
    )
    idSource: str = Field(
        ...,
        description="Indicates which identifier was used as the primary 'id'. One of: 'pulse:githubRepositoryHandle', 'schema:citation', or 'uuid'",
    )
    schema_name: str = Field(
        ...,
        alias="schema:name",
        description="Repository display name. REQUIRED per SHACL. Example: 'Open Pulse Platform'",
    )
    pulse_githubRepositoryHandle: str = Field(
        ...,
        alias="pulse:githubRepositoryHandle",
        description="GitHub repository handle. REQUIRED per SHACL. Format: owner/repo. Example: 'EPFL-ENAC/geodata-toolkit'",
    )
    pulse_repositoryType: PulseRepositoryType | None = Field(
        None,
        alias="pulse:repositoryType",
        description="Type of repository. One of: 'pulse:Software', 'pulse:Data', 'pulse:Documentation', 'pulse:EducationalResource', 'pulse:Other'",
    )
    pulse_discipline: list[PulseDisciplineEnum] | None = Field(
        None,
        alias="pulse:discipline",
        description="Array of Wikidata IRIs for disciplines. Format: wd:QXXXXX. Example: ['wd:Q21201', 'wd:Q8434']",
    )
    schema_author: list[str] = Field(
        ...,
        alias="schema:author",
        description="Array of PersonShape IDs (hierarchical). REQUIRED per SHACL (min 1 author). Example: ['0000-0001-2345-6789', 'mweber']",
        min_length=1,
    )
    pulse_githubRepoStars: int | None = Field(
        None,
        alias="pulse:githubRepoStars",
        description="GitHub star count. Example: 45",
    )
    pulse_githubRepoForks: int | None = Field(
        None,
        alias="pulse:githubRepoForks",
        description="GitHub fork count. Example: 12",
    )
    schema_dateCreated: str | None = Field(
        None,
        alias="schema:dateCreated",
        description="Creation datetime in ISO 8601 format. Format: YYYY-MM-DDTHH:MM:SSZ. Example: '2023-03-15T10:30:00Z'",
    )
    schema_license: str | None = Field(
        None,
        alias="schema:license",
        description="SPDX license IRI. Example: 'https://spdx.org/licenses/MIT.html'",
    )
    schema_citation: str | None = Field(
        None,
        alias="schema:citation",
        description="DOI URL for citation. Example: 'https://doi.org/10.5281/zenodo.12345678'",
    )
    schema_programmingLanguage: list[str] | None = Field(
        None,
        alias="schema:programmingLanguage",
        description="Array of programming languages. Example: ['Python', 'TypeScript']",
    )
    pulse_ownedBy: str | None = Field(
        None,
        alias="pulse:ownedBy",
        description="PersonShape or OrganizationShape ID (hierarchical) that owns this repository. Example: '95372c6b-7d45-432e-a84e-660c9fa54e05'",
    )
    pulse_isForkOf: str | None = Field(
        None,
        alias="pulse:isForkOf",
        description="Parent RepositoryShape ID (GitHub handle) if this is a fork. Example: 'numpy/numpy'",
    )


class Identifiers2(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    pulse_ror: str | None = Field(
        None,
        alias="pulse:ror",
        description="ROR (Research Organization Registry) identifier. Format: https://ror.org/XXXXXXXXX (9 alphanumeric chars). Example: 'https://ror.org/02s376052'",
    )
    pulse_infoscienceOrganizationIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceOrganizationIdentifier",
        description="Infoscience organization UUID4 identifier. Format: 8-4-4-4-12 hexadecimal characters. Example: '95372c6b-7d45-432e-a84e-660c9fa54e05'",
    )
    pulse_githubOrganizationHandle: str | None = Field(
        None,
        alias="pulse:githubOrganizationHandle",
        description="GitHub organization handle. Example: 'EPFL-ENAC'",
    )
    uuid: str | None = Field(
        None,
        description="UUID4 fallback identifier. Always present. Example: 'e2c4b6a8-1d3f-4e5a-9b7c-8d6e4f2a1b3c'",
    )


class PulseOrganizationType(Enum):
    pulse_University = "pulse:University"
    pulse_ResearchInstitution = "pulse:ResearchInstitution"
    pulse_GovernmentAgency = "pulse:GovernmentAgency"
    pulse_SoftwareProject = "pulse:SoftwareProject"
    pulse_PrivateCompany = "pulse:PrivateCompany"
    pulse_NonProfitOrganization = "pulse:NonProfitOrganization"
    pulse_CommunitySpace = "pulse:CommunitySpace"
    pulse_OtherOrganizationType = "pulse:OtherOrganizationType"


class AgentOrganizationShape(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier. Set to the first non-null value from: pulse:ror, pulse:infoscienceOrganizationIdentifier, pulse:githubOrganizationHandle, or uuid (fallback). Example: 'https://ror.org/02s376052' or 'numpy'",
    )
    type: str = Field(..., description="RDF type. Must be 'org:Organization'")
    shacl: str = Field(
        ..., description="SHACL shape reference. Must be 'pulse:OrganizationShape'"
    )
    identifiers: Identifiers2 = Field(
        ...,
        description="All available identifiers for this organization. Contains pulse:ror, pulse:infoscienceOrganizationIdentifier, pulse:githubOrganizationHandle, and uuid",
    )
    idSource: str = Field(
        ...,
        description="Indicates which identifier was used as the primary 'id'. One of: 'pulse:ror', 'pulse:infoscienceOrganizationIdentifier', 'pulse:githubOrganizationHandle', or 'uuid'",
    )
    schema_name: str = Field(
        ...,
        alias="schema:name",
        description="Organization name. Example: 'École Polytechnique Fédérale de Lausanne'",
    )
    schema_identifier: str | None = Field(
        None,
        alias="schema:identifier",
        description="Canonical identifier (typically ROR URL). Example: 'https://ror.org/02s376052'",
    )
    pulse_githubOrganizationHandle: str | None = Field(
        None,
        alias="pulse:githubOrganizationHandle",
        description="GitHub organization handle. Example: 'EPFL-ENAC'",
    )
    pulse_infoscienceOrganizationIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceOrganizationIdentifier",
        description="Infoscience organization identifier (UUID format). Example: '41674f42-ba15-4612-9817-2a6f60985c01'",
    )
    pulse_OrganizationType: PulseOrganizationType | None = Field(
        None,
        alias="pulse:OrganizationType",
        description="Type of organization. One of: 'pulse:University', 'pulse:ResearchInstitution', 'pulse:GovernmentAgency', 'pulse:SoftwareProject', 'pulse:PrivateCompany', 'pulse:NonProfitOrganization', 'pulse:CommunitySpace', 'pulse:OtherOrganizationType'",
    )
    pulse_githubOrgFollowers: int | None = Field(
        None,
        alias="pulse:githubOrgFollowers",
        description="GitHub organization follower count. Example: 342",
    )
    org_hasUnit: list[str] | None = Field(
        None,
        alias="org:hasUnit",
        description="Array of child OrganizationShape IDs (hierarchical). Example: ['95372c6b-7d45-432e-a84e-660c9fa54e05']",
    )
    org_unitOf: list[str] | None = Field(
        None,
        alias="org:unitOf",
        description="Parent OrganizationShape IDs (hierarchical). Most orgs have 0 or 1 parent; arrays support joint affiliations (e.g. a research center jointly run by two universities). Example: ['https://ror.org/02s376052']",
    )
    pulse_owns: list[str] | None = Field(
        None,
        alias="pulse:owns",
        description="Array of RepositoryShape IDs (GitHub handles) owned by this organization. Example: ['EPFL-ENAC/geodata-toolkit']",
    )


class Identifiers3(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    pulse_composite: str | None = Field(
        None,
        alias="pulse:composite",
        description="Composite identifier. Format: personId_orgId (uses underscore separator). Example: '0000-0001-2345-6789_https://ror.org/02s376052'",
    )
    uuid: str | None = Field(
        None,
        description="UUID4 fallback identifier. Always present. Example: 'c1a2b3c4-5d6e-4f7a-8b9c-0d1e2f3a4b5c'",
    )


class AgentMembershipShape(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier. Composite format: personId_orgId, or uuid (fallback). Example: '0000-0001-2345-6789_https://ror.org/02s376052'",
    )
    type: str = Field(..., description="RDF type. Must be 'org:Membership'")
    shacl: str = Field(
        ..., description="SHACL shape reference. Must be 'pulse:MembershipShape'"
    )
    identifiers: Identifiers3 = Field(
        ...,
        description="All available identifiers for this membership. Contains pulse:composite and uuid",
    )
    idSource: str = Field(
        ...,
        description="Indicates which identifier was used as the primary 'id'. One of: 'pulse:composite' or 'uuid'",
    )
    org_organization: str = Field(
        ...,
        alias="org:organization",
        description="Reference to OrganizationShape ID (hierarchical). REQUIRED per SHACL. Example: 'https://ror.org/02s376052'",
    )
    org_role: str | None = Field(
        None,
        alias="org:role",
        description="Role or position title within the organization. OPTIONAL per SHACL. Example: 'Research Engineer', 'PhD Student'",
    )
    time_hasBeginning: str | None = Field(
        None,
        alias="time:hasBeginning",
        description="Start date of membership. Format: ISO 8601 date (YYYY-MM-DD). Example: '2020-09-01'",
    )
    time_hasEnd: str | None = Field(
        None,
        alias="time:hasEnd",
        description="End date of membership. Format: ISO 8601 date (YYYY-MM-DD). Null if current/ongoing. Example: '2024-02-28'",
    )


class Identifiers4(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    pulse_composite: str | None = Field(
        None,
        alias="pulse:composite",
        description="Composite identifier. Format: personId_repoId (uses underscore separator). Example: '0000-0001-2345-6789_EPFL-ENAC/geodata-toolkit'",
    )
    uuid: str | None = Field(
        None,
        description="UUID4 fallback identifier. Always present. Example: 'd1a2b3c4-5e6f-4a7b-8c9d-0e1f2a3b4c5d'",
    )


class AgentContributionShape(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier. Composite format: personId_repoId, or uuid (fallback). Example: '0000-0001-2345-6789_EPFL-ENAC/geodata-toolkit'",
    )
    type: str = Field(..., description="RDF type. Must be 'pulse:Contribution'")
    shacl: str = Field(
        ..., description="SHACL shape reference. Must be 'pulse:ContributionShape'"
    )
    identifiers: Identifiers4 = Field(
        ...,
        description="All available identifiers for this contribution. Contains pulse:composite and uuid",
    )
    idSource: str = Field(
        ...,
        description="Indicates which identifier was used as the primary 'id'. One of: 'pulse:composite' or 'uuid'",
    )
    pulse_contributionTo: str = Field(
        ...,
        alias="pulse:contributionTo",
        description="Reference to RepositoryShape ID (GitHub handle). REQUIRED per SHACL. Example: 'EPFL-ENAC/geodata-toolkit'",
    )
    pulse_contributionCount: int = Field(
        ...,
        alias="pulse:contributionCount",
        description="Number of commits/contributions. REQUIRED per SHACL. Must be zero or positive. Example: 156",
    )
    pulse_firstContributionDate: str | None = Field(
        None,
        alias="pulse:firstContributionDate",
        description="First contribution datetime. OPTIONAL per SHACL. Format: ISO 8601 datetime (YYYY-MM-DDTHH:MM:SSZ). Example: '2023-03-15T10:30:00Z'",
    )
    pulse_lastContributionDate: str | None = Field(
        None,
        alias="pulse:lastContributionDate",
        description="Last contribution datetime. OPTIONAL per SHACL. Format: ISO 8601 datetime (YYYY-MM-DDTHH:MM:SSZ). Example: '2025-01-20T14:45:00Z'",
    )
    schema_author: str = Field(
        ...,
        alias="schema:author",
        description="Reference to PersonShape ID (hierarchical). REQUIRED per SHACL. Example: '0000-0001-2345-6789'",
    )


class Identifiers5(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    schema_identifier: str | None = Field(
        None,
        alias="schema:identifier",
        description="DOI identifier. Format: 10.XXXX/suffix. Example: '10.1038/s41586-024-07856-z'",
    )
    pulse_infoscienceArticleIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceArticleIdentifier",
        description="Infoscience article UUID4 identifier. Format: 8-4-4-4-12 hexadecimal characters. Example: 'f97b60da-bcab-4f2e-ba12-0ee0c4d0d6eb'",
    )
    uuid: str | None = Field(
        None,
        description="UUID4 fallback identifier. Always present. Example: 'f8a3b2c1-4d5e-4f6a-8b9c-1d2e3f4a5b6c'",
    )


class AgentArticleShape(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier. Set to the first non-null value from: schema:identifier (DOI), pulse:infoscienceArticleIdentifier, or uuid (fallback). Example: '10.1038/s41586-024-07856-z'",
    )
    type: str = Field(..., description="RDF type. Must be 'schema:ScholarlyArticle'")
    shacl: str = Field(
        ..., description="SHACL shape reference. Must be 'pulse:ArticleShape'"
    )
    identifiers: Identifiers5 = Field(
        ...,
        description="All available identifiers for this article. Contains schema:identifier (DOI), pulse:infoscienceArticleIdentifier, and uuid",
    )
    idSource: str = Field(
        ...,
        description="Indicates which identifier was used as the primary 'id'. One of: 'schema:identifier', 'pulse:infoscienceArticleIdentifier', or 'uuid'",
    )
    schema_name: str = Field(
        ...,
        alias="schema:name",
        description="Article title. REQUIRED per SHACL. Example: 'Open Pulse: A Framework for Tracking Scientific Software Contributions'",
    )
    schema_identifier: str = Field(
        ...,
        alias="schema:identifier",
        description="DOI identifier. REQUIRED per SHACL. Format: 10.XXXX/suffix. Example: '10.1038/s41586-024-07856-z'",
    )
    schema_datePublished: str = Field(
        ...,
        alias="schema:datePublished",
        description="Publication date. REQUIRED per SHACL. Format: ISO 8601 date (YYYY-MM-DD). Example: '2025-06-15'",
    )
    schema_author: list[str] = Field(
        ...,
        alias="schema:author",
        description="Array of PersonShape hierarchical IDs. REQUIRED per SHACL (min 1 author). Uses target's resolved id (could be ORCID, GitHub username, or UUID). Example: ['0000-0001-2345-6789', 'mweber']",
        min_length=1,
    )
    pulse_infoscienceArticleIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceArticleIdentifier",
        description="Infoscience article UUID4 identifier. Example: 'f97b60da-bcab-4f2e-ba12-0ee0c4d0d6eb'",
    )
    schema_sourceOrganization: str | None = Field(
        None,
        alias="schema:sourceOrganization",
        description="Reference to OrganizationShape hierarchical ID. Uses target's resolved id (could be ROR, GitHub org handle, or UUID). Example: 'https://ror.org/02s376052'",
    )


class AgentEntitiesBundle(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    agentpersonshape: AgentPersonShape | None = None
    agentrepositoryshape: AgentRepositoryShape | None = None
    agentorganizationshape: AgentOrganizationShape | None = None
    agentmembershipshape: AgentMembershipShape | None = None
    agentcontributionshape: AgentContributionShape | None = None
    agentarticleshape: AgentArticleShape | None = None
