# generated by datamodel-codegen:
#   filename:  bundle.schema.json
# source-schema-sha256:
# - article.schema.json: 705c607bd70f982d4b186b7033d41cdc8f74ec86e68f2c6d6ab86c87ce29b4bd
# - contribution.schema.json: 39db27096c58d615240bb69152a84eba68ac503fd9f2000d16ee045305f2ef38
# - membership.schema.json: c3c9b9e8743bb3e4f199b998cffc9ddf481ce787a7de8f45db6317217581c20d
# - organization.schema.json: 5a2acdb26373aa487b3f859eb997e6ea3dffdaf5448543e61d0214c40cc7014c
# - person.schema.json: 789285c972eaeeece7926ea68b0b0e0088cabeb8c9b234974fe7f9aab437290c
# - repository.schema.json: 0bf4dacdf49adad5be9d77dc233973076de977485d6aa10c6833cf561b725645
#

from __future__ import annotations
from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel
from enum import Enum
from typing import Literal


class Identifiers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pulse_orcid: str | None = Field(
        None, alias="pulse:orcid", pattern="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$"
    )
    pulse_infosciencePersonIdentifier: str | None = Field(
        None,
        alias="pulse:infosciencePersonIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    pulse_githubUsername: str | None = Field(None, alias="pulse:githubUsername")
    uuid: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )


class IdSource(Enum):
    pulse_orcid = "pulse:orcid"
    pulse_infosciencePersonIdentifier = "pulse:infosciencePersonIdentifier"
    pulse_githubUsername = "pulse:githubUsername"
    uuid = "uuid"


class PersonModel1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: orcid → infosciencePersonIdentifier → githubUsername → uuid)",
    )
    type: Literal["schema:Person"]
    shacl: Literal["pulse:PersonShape"]
    identifiers: Identifiers
    idSource: IdSource
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_email: str | None = Field(
        None, alias="schema:email", pattern="^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
    )
    schema_url: AnyUrl | None = Field(None, alias="schema:url")
    pulse_githubUsername: str = Field(..., alias="pulse:githubUsername")
    pulse_orcidIdentifier: str | None = Field(
        None,
        alias="pulse:orcidIdentifier",
        pattern="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$",
    )
    pulse_infosciencePersonIdentifier: str | None = Field(
        None,
        alias="pulse:infosciencePersonIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    org_hasMembership: list[str] | None = Field(None, alias="org:hasMembership")
    pulse_hasContribution: list[str] | None = Field(None, alias="pulse:hasContribution")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class PersonModel2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: orcid → infosciencePersonIdentifier → githubUsername → uuid)",
    )
    type: Literal["schema:Person"]
    shacl: Literal["pulse:PersonShape"]
    identifiers: Identifiers
    idSource: IdSource
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_email: str = Field(
        ..., alias="schema:email", pattern="^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
    )
    schema_url: AnyUrl | None = Field(None, alias="schema:url")
    pulse_githubUsername: str | None = Field(None, alias="pulse:githubUsername")
    pulse_orcidIdentifier: str | None = Field(
        None,
        alias="pulse:orcidIdentifier",
        pattern="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$",
    )
    pulse_infosciencePersonIdentifier: str | None = Field(
        None,
        alias="pulse:infosciencePersonIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    org_hasMembership: list[str] | None = Field(None, alias="org:hasMembership")
    pulse_hasContribution: list[str] | None = Field(None, alias="pulse:hasContribution")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class PersonModel3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: orcid → infosciencePersonIdentifier → githubUsername → uuid)",
    )
    type: Literal["schema:Person"]
    shacl: Literal["pulse:PersonShape"]
    identifiers: Identifiers
    idSource: IdSource
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_email: str | None = Field(
        None, alias="schema:email", pattern="^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
    )
    schema_url: AnyUrl | None = Field(None, alias="schema:url")
    pulse_githubUsername: str | None = Field(None, alias="pulse:githubUsername")
    pulse_orcidIdentifier: str | None = Field(
        None,
        alias="pulse:orcidIdentifier",
        pattern="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$",
    )
    pulse_infosciencePersonIdentifier: str = Field(
        ...,
        alias="pulse:infosciencePersonIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    org_hasMembership: list[str] | None = Field(None, alias="org:hasMembership")
    pulse_hasContribution: list[str] | None = Field(None, alias="pulse:hasContribution")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class PersonModel4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: orcid → infosciencePersonIdentifier → githubUsername → uuid)",
    )
    type: Literal["schema:Person"]
    shacl: Literal["pulse:PersonShape"]
    identifiers: Identifiers
    idSource: IdSource
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_email: str | None = Field(
        None, alias="schema:email", pattern="^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
    )
    schema_url: AnyUrl | None = Field(None, alias="schema:url")
    pulse_githubUsername: str | None = Field(None, alias="pulse:githubUsername")
    pulse_orcidIdentifier: str = Field(
        ...,
        alias="pulse:orcidIdentifier",
        pattern="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$",
    )
    pulse_infosciencePersonIdentifier: str | None = Field(
        None,
        alias="pulse:infosciencePersonIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    org_hasMembership: list[str] | None = Field(None, alias="org:hasMembership")
    pulse_hasContribution: list[str] | None = Field(None, alias="pulse:hasContribution")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class PersonModel(RootModel[PersonModel1 | PersonModel2 | PersonModel3 | PersonModel4]):
    root: PersonModel1 | PersonModel2 | PersonModel3 | PersonModel4 = Field(
        ...,
        description="Schema for validating Person entities following Open Pulse Ontology v2.1.2. ID hierarchy: orcid → infosciencePersonIdentifier → githubUsername → uuid",
        title="PersonModel",
    )


class Identifiers4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pulse_githubRepositoryHandle: str = Field(
        ...,
        alias="pulse:githubRepositoryHandle",
        pattern="^[a-zA-Z0-9\\-_]+/[a-zA-Z0-9\\-_\\.]+$",
    )
    schema_citation: AnyUrl | None = Field(
        None, alias="schema:citation", description="DOI identifier"
    )
    uuid: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )


class IdSource4(Enum):
    pulse_githubRepositoryHandle = "pulse:githubRepositoryHandle"
    schema_citation = "schema:citation"
    uuid = "uuid"


class PulseRepositoryType(Enum):
    pulse_Software = "pulse:Software"
    pulse_Data = "pulse:Data"
    pulse_Documentation = "pulse:Documentation"
    pulse_EducationalResource = "pulse:EducationalResource"
    pulse_Other = "pulse:Other"


class PulseDisciplineEnum(Enum):
    wd_Q1254373 = "wd:Q1254373"
    wd_Q101333 = "wd:Q101333"
    wd_Q1071 = "wd:Q1071"
    wd_Q11680831 = "wd:Q11680831"
    wd_Q12271 = "wd:Q12271"
    wd_Q12483 = "wd:Q12483"
    wd_Q18351432 = "wd:Q18351432"
    wd_Q188847 = "wd:Q188847"
    wd_Q192386 = "wd:Q192386"
    wd_Q21201 = "wd:Q21201"
    wd_Q2167061 = "wd:Q2167061"
    wd_Q2329 = "wd:Q2329"
    wd_Q23404 = "wd:Q23404"
    wd_Q2878974 = "wd:Q2878974"
    wd_Q309 = "wd:Q309"
    wd_Q333 = "wd:Q333"
    wd_Q3353193 = "wd:Q3353193"
    wd_Q34749 = "wd:Q34749"
    wd_Q3606845 = "wd:Q3606845"
    wd_Q395 = "wd:Q395"
    wd_Q413 = "wd:Q413"
    wd_Q420 = "wd:Q420"
    wd_Q42240 = "wd:Q42240"
    wd_Q428691 = "wd:Q428691"
    wd_Q43035 = "wd:Q43035"
    wd_Q4830453 = "wd:Q4830453"
    wd_Q580689 = "wd:Q580689"
    wd_Q5891 = "wd:Q5891"
    wd_Q7112556 = "wd:Q7112556"
    wd_Q7163 = "wd:Q7163"
    wd_Q735 = "wd:Q735"
    wd_Q7748 = "wd:Q7748"
    wd_Q77590 = "wd:Q77590"
    wd_Q7991 = "wd:Q7991"
    wd_Q8008 = "wd:Q8008"
    wd_Q80083 = "wd:Q80083"
    wd_Q8078 = "wd:Q8078"
    wd_Q8134 = "wd:Q8134"
    wd_Q8162 = "wd:Q8162"
    wd_Q816264 = "wd:Q816264"
    wd_Q8242 = "wd:Q8242"
    wd_Q83588 = "wd:Q83588"
    wd_Q8434 = "wd:Q8434"
    wd_Q843601 = "wd:Q843601"
    wd_Q9174 = "wd:Q9174"
    wd_Q9418 = "wd:Q9418"


class RepositoryModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: githubRepositoryHandle → doi → uuid)",
    )
    type: Literal["schema:SoftwareSourceCode"]
    shacl: Literal["pulse:RepositoryShape"]
    identifiers: Identifiers4
    idSource: IdSource4
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    pulse_githubRepositoryHandle: str = Field(
        ...,
        alias="pulse:githubRepositoryHandle",
        pattern="^[a-zA-Z0-9\\-_]+/[a-zA-Z0-9\\-_\\.]+$",
    )
    pulse_repositoryType: PulseRepositoryType | None = Field(
        None,
        alias="pulse:repositoryType",
        description="Repository type. Optional per SHACL.",
    )
    pulse_discipline: list[PulseDisciplineEnum] | None = Field(
        None, alias="pulse:discipline"
    )
    schema_author: list[str] = Field(..., alias="schema:author", min_length=1)
    pulse_githubRepoStars: int | None = Field(None, alias="pulse:githubRepoStars", ge=0)
    pulse_githubRepoForks: int | None = Field(None, alias="pulse:githubRepoForks", ge=0)
    schema_dateCreated: str | None = Field(
        None,
        alias="schema:dateCreated",
        description="ISO 8601 datetime format",
        pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
    )
    schema_license: AnyUrl | None = Field(
        None, alias="schema:license", description="SPDX license IRI"
    )
    schema_citation: AnyUrl | None = Field(
        None, alias="schema:citation", description="DOI URL for citation"
    )
    schema_programmingLanguage: list[str] | None = Field(
        None, alias="schema:programmingLanguage"
    )
    pulse_ownedBy: str | None = Field(
        None,
        alias="pulse:ownedBy",
        description="Reference to PersonShape or OrganizationShape ID (hierarchical)",
    )
    pulse_isForkOf: str | None = Field(
        None,
        alias="pulse:isForkOf",
        description="Reference to parent RepositoryShape ID (GitHub handle)",
    )


class Identifiers5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pulse_ror: str | None = Field(
        None, alias="pulse:ror", pattern="^https://ror\\.org/[0-9a-z]{9}$"
    )
    pulse_infoscienceOrganizationIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceOrganizationIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    pulse_githubOrganizationHandle: str | None = Field(
        None, alias="pulse:githubOrganizationHandle"
    )
    uuid: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )


class IdSource5(Enum):
    pulse_ror = "pulse:ror"
    pulse_infoscienceOrganizationIdentifier = "pulse:infoscienceOrganizationIdentifier"
    pulse_githubOrganizationHandle = "pulse:githubOrganizationHandle"
    uuid = "uuid"


class PulseOrganizationType(Enum):
    pulse_University = "pulse:University"
    pulse_ResearchInstitution = "pulse:ResearchInstitution"
    pulse_GovernmentAgency = "pulse:GovernmentAgency"
    pulse_SoftwareProject = "pulse:SoftwareProject"
    pulse_PrivateCompany = "pulse:PrivateCompany"
    pulse_NonProfitOrganization = "pulse:NonProfitOrganization"
    pulse_CommunitySpace = "pulse:CommunitySpace"
    pulse_OtherOrganizationType = "pulse:OtherOrganizationType"


class OrganizationModel1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: ror → infoscienceOrganizationIdentifier → githubOrganizationHandle → uuid)",
    )
    type: Literal["org:Organization"]
    shacl: Literal["pulse:OrganizationShape"]
    identifiers: Identifiers5
    idSource: IdSource5
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_identifier: str = Field(
        ...,
        alias="schema:identifier",
        description="Canonical identifier (typically ROR URL). Optional per SHACL.",
        pattern="^https://ror\\.org/[0-9a-z]{9}$",
    )
    pulse_githubOrganizationHandle: str | None = Field(
        None, alias="pulse:githubOrganizationHandle"
    )
    pulse_infoscienceOrganizationIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceOrganizationIdentifier",
        description="Infoscience organization identifier (UUID4 format).",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    pulse_OrganizationType: PulseOrganizationType | None = Field(
        None, alias="pulse:OrganizationType"
    )
    pulse_githubOrgFollowers: int | None = Field(
        None, alias="pulse:githubOrgFollowers", ge=0
    )
    org_hasUnit: list[str] | None = Field(None, alias="org:hasUnit")
    org_unitOf: list[str] | None = Field(None, alias="org:unitOf")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class OrganizationModel2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: ror → infoscienceOrganizationIdentifier → githubOrganizationHandle → uuid)",
    )
    type: Literal["org:Organization"]
    shacl: Literal["pulse:OrganizationShape"]
    identifiers: Identifiers5
    idSource: IdSource5
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_identifier: str | None = Field(
        None,
        alias="schema:identifier",
        description="Canonical identifier (typically ROR URL). Optional per SHACL.",
        pattern="^https://ror\\.org/[0-9a-z]{9}$",
    )
    pulse_githubOrganizationHandle: str = Field(
        ..., alias="pulse:githubOrganizationHandle"
    )
    pulse_infoscienceOrganizationIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceOrganizationIdentifier",
        description="Infoscience organization identifier (UUID4 format).",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    pulse_OrganizationType: PulseOrganizationType | None = Field(
        None, alias="pulse:OrganizationType"
    )
    pulse_githubOrgFollowers: int | None = Field(
        None, alias="pulse:githubOrgFollowers", ge=0
    )
    org_hasUnit: list[str] | None = Field(None, alias="org:hasUnit")
    org_unitOf: list[str] | None = Field(None, alias="org:unitOf")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class OrganizationModel3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: ror → infoscienceOrganizationIdentifier → githubOrganizationHandle → uuid)",
    )
    type: Literal["org:Organization"]
    shacl: Literal["pulse:OrganizationShape"]
    identifiers: Identifiers5
    idSource: IdSource5
    schema_name: str = Field(..., alias="schema:name", min_length=1)
    schema_identifier: str | None = Field(
        None,
        alias="schema:identifier",
        description="Canonical identifier (typically ROR URL). Optional per SHACL.",
        pattern="^https://ror\\.org/[0-9a-z]{9}$",
    )
    pulse_githubOrganizationHandle: str | None = Field(
        None, alias="pulse:githubOrganizationHandle"
    )
    pulse_infoscienceOrganizationIdentifier: str = Field(
        ...,
        alias="pulse:infoscienceOrganizationIdentifier",
        description="Infoscience organization identifier (UUID4 format).",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    pulse_OrganizationType: PulseOrganizationType | None = Field(
        None, alias="pulse:OrganizationType"
    )
    pulse_githubOrgFollowers: int | None = Field(
        None, alias="pulse:githubOrgFollowers", ge=0
    )
    org_hasUnit: list[str] | None = Field(None, alias="org:hasUnit")
    org_unitOf: list[str] | None = Field(None, alias="org:unitOf")
    pulse_owns: list[str] | None = Field(None, alias="pulse:owns")


class OrganizationModel(
    RootModel[OrganizationModel1 | OrganizationModel2 | OrganizationModel3]
):
    root: OrganizationModel1 | OrganizationModel2 | OrganizationModel3 = Field(
        ...,
        description="Schema for validating Organization entities following Open Pulse Ontology v2.1.2. ID hierarchy: ror → infoscienceOrganizationIdentifier → githubOrganizationHandle → uuid. SHACL requires: schema:name AND at least ONE of (schema:identifier, pulse:githubOrganizationHandle, pulse:infoscienceOrganizationIdentifier).",
        title="OrganizationModel",
    )


class Identifiers8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pulse_composite: str = Field(
        ...,
        alias="pulse:composite",
        description="Composite identifier in format: personId_orgId",
    )
    uuid: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )


class IdSource8(Enum):
    pulse_composite = "pulse:composite"
    uuid = "uuid"


class MembershipModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (composite format: personId_orgId, or uuid fallback)",
    )
    type: Literal["org:Membership"]
    shacl: Literal["pulse:MembershipShape"]
    identifiers: Identifiers8
    idSource: IdSource8
    org_organization: str = Field(
        ...,
        alias="org:organization",
        description="Reference to OrganizationShape ID (hierarchical)",
    )
    org_role: str | None = Field(
        None,
        alias="org:role",
        description="Role or position title within the organization. Optional per SHACL (maxCount 1).",
    )
    time_hasBeginning: str | None = Field(
        None,
        alias="time:hasBeginning",
        description="Start date in ISO 8601 date format (YYYY-MM-DD)",
        pattern="^\\d{4}-\\d{2}-\\d{2}$",
    )
    time_hasEnd: str | None = Field(
        None,
        alias="time:hasEnd",
        description="End date in ISO 8601 date format (YYYY-MM-DD)",
        pattern="^\\d{4}-\\d{2}-\\d{2}$",
    )


class Identifiers9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pulse_composite: str = Field(
        ...,
        alias="pulse:composite",
        description="Composite identifier in format: personId_repoId",
    )
    uuid: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )


class ContributionModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (composite format: personId_repoId, or uuid fallback)",
    )
    type: Literal["pulse:Contribution"]
    shacl: Literal["pulse:ContributionShape"]
    identifiers: Identifiers9
    idSource: IdSource8
    pulse_contributionTo: str = Field(
        ...,
        alias="pulse:contributionTo",
        description="Reference to RepositoryShape ID (GitHub handle format: owner/repo)",
    )
    pulse_contributionCount: int = Field(
        ...,
        alias="pulse:contributionCount",
        description="Number of commits/contributions",
        ge=0,
    )
    pulse_firstContributionDate: str | None = Field(
        None,
        alias="pulse:firstContributionDate",
        description="First contribution datetime in ISO 8601 format. Optional per SHACL.",
        pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
    )
    pulse_lastContributionDate: str | None = Field(
        None,
        alias="pulse:lastContributionDate",
        description="Last contribution datetime in ISO 8601 format. Optional per SHACL.",
        pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
    )
    schema_author: str = Field(
        ...,
        alias="schema:author",
        description="Reference to PersonShape ID (hierarchical)",
    )


class Identifiers10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_identifier: str = Field(
        ...,
        alias="schema:identifier",
        description="DOI identifier (required per SHACL minCount 1)",
        pattern="^10\\.\\d{4,9}/[-._;()/:a-zA-Z0-9]+$",
    )
    pulse_infoscienceArticleIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceArticleIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    uuid: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )


class IdSource10(Enum):
    schema_identifier = "schema:identifier"
    pulse_infoscienceArticleIdentifier = "pulse:infoscienceArticleIdentifier"
    uuid = "uuid"


class ArticleModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="Resolved hierarchical identifier (first non-null in priority: doi → infoscienceArticleIdentifier → uuid)",
    )
    type: Literal["schema:ScholarlyArticle"]
    shacl: Literal["pulse:ArticleShape"]
    identifiers: Identifiers10
    idSource: IdSource10
    schema_name: str = Field(
        ..., alias="schema:name", description="Article title", min_length=1
    )
    schema_identifier: str = Field(
        ...,
        alias="schema:identifier",
        description="DOI identifier (required per SHACL minCount 1)",
        pattern="^10\\.\\d{4,9}/[-._;()/:a-zA-Z0-9]+$",
    )
    schema_datePublished: str = Field(
        ...,
        alias="schema:datePublished",
        description="Publication date in ISO 8601 date format (YYYY-MM-DD)",
        pattern="^\\d{4}-\\d{2}-\\d{2}$",
    )
    schema_author: list[str] = Field(..., alias="schema:author", min_length=1)
    pulse_infoscienceArticleIdentifier: str | None = Field(
        None,
        alias="pulse:infoscienceArticleIdentifier",
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    schema_sourceOrganization: str | None = Field(
        None,
        alias="schema:sourceOrganization",
        description="Reference to OrganizationShape hierarchical ID (ror, infoscienceOrganizationIdentifier, githubOrganizationHandle, or uuid)",
    )


class EntitiesBundle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    personmodel: PersonModel | None = None
    repositorymodel: RepositoryModel | None = None
    organizationmodel: OrganizationModel | None = None
    membershipmodel: MembershipModel | None = None
    contributionmodel: ContributionModel | None = None
    articlemodel: ArticleModel | None = None
